indent_style = "Visual"
brace_style = "SameLineWhere"
fn_args_density = "Tall"
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
report_todo = "Never"
report_fixme = "Never"
wrap_comments = true
use_try_shorthand = true
max_width = 100
trailing_comma = "Never"
condense_wildcard_suffixes = true
error_on_line_overflow = true
force_explicit_abi = true
format_strings = true
hard_tabs = false
imports_indent = "Visual"
imports_layout = "Mixed"
match_block_trailing_comma = false
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = false
trailing_semicolon = false
write_mode = "Overwrite"
